### ISSUE TITLE
[Needs Discussion] Options For Helping Salvage Monotony

### ISSUE THREAD

**Issue by PursuitInAshes** [cosmatic-drift-14/cosmatic-drift#44]
### Information/Previous Discussion 
The discord user SpectralSpices has brought up a feeling of monotony when it comes to salvage currently due to the weighting of salvage wrecks being morso to randomly generated asteroids. This issue is to discuss ways we could potentially relieve that, or if its a non-issue.

### Proposed Solutions
1) Rebalance the weighting/chances of wrecks. Currently, to my understanding, its weighted to be more so for asteroids due to balancing. This is probably the worst of the options, at least in my opinion.

2) Adding additional magnet options/magnet type. Salvagers could change the magnet (Likely through a verb) to set it to only pull in specific wreck types (Currently only debris and asteroids), but this would drastically increase the cooldown of the magnet as well as potentially a timer to bring in the wreck. The original both debris and asteroid option would remain. The cooldown extension would purely be for balancing,

So, the question is now the following:

Is this even an issue to begin with, how much of the community this monotonous feeling when doing salvage?
If its an issue, which option are we going to assume is best to implement to fix it, is there a third or fourth option?

**Comment by Tych0theSynth** [comment]
I've been thinking a lot about this over the past week. Salvage is probably my favourite role alongside detective, and adding some more flavour to the role has the potential to add some good things, maybe even allow other departments to have some more involvement.

Salvage does have a tendency to drag a bit, especially if you're running solo and only realistically able to do magnet runs. For teams focusing on expeditions, there's always more loot, but there's not necessarily much that the station NEEDS when cargo is rich, you've got cloning etc.
For me, just going on the expedition and exploring is where most of the fun lies for me.

Overall, I feel like salvage does have even more potential to become monotonous with the shift times we can expect to see in this fork.

I agree that point 1 is not a good option. 

With regards to point two:
How about an advanced salvage magnet, locked behind sci research (tier 2?)? It would have its own board so can be built in situ, and could have the ability to attune to particular types of salvage. Want roids? Attune it to roids and the chance of getting a roid is now significantly higher and vice versa for station debris.

Perhaps it could be an upgradable machine. Upgrades could influence:
- Increased hold time.
- Higher chance of rare debris (good for endgame salvaging).

The main tradeoff being that the cooldown would be higher than the regular magnet, and this cannot be reduced. However, this feels like a fair trade-off for the ability to choose debris and have more time on it.

Obviously there would need to be some way of preventing multiple magents from being used, as that could easily be powergamed.

Another thought I'd had was some kinda expansion to being marooned on the expedition planet. 
Right now it's just 'vwoop, you're gone' and that's it. Salvage is of course meant to be high risk, and it should stay that way, but maybe we could consider an emergency beacon or emergency teleport of sorts for salvagers.
Again, sci research locked, requires a fuel of sorts to charge it (it shouldn't be something cheap) and it's a machine installed on The Reclaimer that teleports any alive salvagers that aren't on board onto the ship when the expedition timer runs out, and teleports any dead ones at the moment of death. Cost could be per salvager.
Could be too powerful, possibly. I don't want to take the risk out of the job, because the risk is what makes it so much fun. Might be nice to have a bit of insurance for when things go REALLY wrong, however, so the department isn't just...empty.

Little bit of a brain dump, but these are my thoughts so far.

**Comment by Tych0theSynth** [comment]
> It seems like this is partially upstream as well as the extended roundtimers for here. I think I have a couple ideas of what we could do to help with this, and I'll probably throw them in a design document or another issue once people are done discussing here, we'll see.

Agree. The increased exped time is such an enormous breath of fresh air. As a frequent salvor, it's so nice to be able to have time to just explore the planet and rp with the team instead of rushing to grab as much as possible.

> I think this is what I'm leaning towards, its what I was thinking with point 2, just put in some clearer words. I think an increased hold time upgrade might be a bit weird, but not impossible. An additional trade-off that I strongly recommend would be increasing the cooldown in-between uses if you are pulling in a specific type of debris. I agree here, for the most part.

Oh yeah, increasing the cooldown is a must. Would be too powerful otherwise.

> The simple way to do this would be to give magnets a global cooldown. Use one and it causes both to be on cooldown. Use one that has a higher cooldown? It applies to both.

Agree. Simplest and best way.

> A guaranteed teleport seems a bit strong and the timer on expeditions should still be an active threat. I wouldn't be opposed to a research that allows salvagers a beacon, like you said, that for a limited time will allow shuttles to return to that expedition planet. Though this should probably be a pretty expensive research. A teleporter doesn't make a whole lot of sense to me, personally. I'm open to a lot, I'd just like to make sure expedition timers are still an active threat.

Maybe we could add an implant that when you die it activates and starts beeping for a few moments? Could be useful to help track down dead/downed salvagers. Once it gets used, or the person is revived, a new one has to be implanted.

Yeah, the teleporting idea felt a bit strong, but I thought I'd just throw it out there.
An emergency beacon would be a simpler and more roleplayable option. Here's a bit of a step by step method on how I envision it working:
1. Salvor dies on the expedition/timer runs out, emergency beacon is activated.
2. Reclaimer flies back and relays the alert in supply comms when it arrives in local space. Expedition planet remains open, maximum of 5-10 mins to allow for travel time and to give someone a chance to recover the body before it rots.
3. Remaining salvors mount a rescue, could also be a good role for a paramedic to get involved in.
4. Fly back, find the guy, retrieve them.
5. Warning on timer running out. If anyone is on the planet when the beacon expires, they suffer the same consequences.
6. Salvor needs a new beacon implant.
